services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    container_name: spotify_api
    ports:
      - "8000:8000"
    restart: unless-stopped

  app:
    build:
      context: ../..
      dockerfile: code/deployment/app/Dockerfile
    container_name: spotify_app
    ports:
      - "8502:8501"
    depends_on:
      - api
    restart: unless-stopped